provider "aws" {
  region = var.region
}

# 🔐 Security Group
resource "aws_security_group" "app_sg" {
  name        = "currency-app-sg"
  description = "Allow HTTP, SSH, API"

  ingress {
    description = "HTTP"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    description = "Backend API"
    from_port   = 3000
    to_port     = 3000
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# 🖥️ EC2 Instance
resource "aws_instance" "app_server" {
  ami           = "ami-0c02fb55956c7d316" # ⚠️ Ubuntu (à changer si besoin)
  instance_type = var.instance_type
  key_name      = var.key_name

  vpc_security_group_ids = [aws_security_group.app_sg.id]

  user_data = <<-EOF
#!/bin/bash
set -e

# Update
apt update -y

# Install base tools
apt install -y git curl nginx

# Install Node.js 20
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt install -y nodejs

# Install PM2
npm install -g pm2

# Clone project
cd /home/ubuntu
git clone https://github.com/YOUR_USERNAME/currency-converter.git
cd currency-converter

# Backend
cd backend
npm install

# Frontend
cd ../frontend
npm install
npm run build

# Deploy frontend to nginx
rm -rf /var/www/html/*
cp -r dist/* /var/www/html/

# Start backend
cd ../backend
pm2 start server.js --name currency-api
pm2 save

# Restart nginx
systemctl restart nginx

EOF

  tags = {
    Name = "currency-converter"
  }
}
