name: Deploy Final
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Déploiement Almalek"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init & Apply
        id: apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: "us-east-1"
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
          echo "L'application est en cours d'installation sur : http://$(terraform output -raw instance_ip)"
